### ISSUE TITLE
i am facing error on firetransfer code 3 after image crop.. and goes for analysing

### ISSUE THREAD

**Issue by adeel399** [hitmacreed/Image-Recognition-ionic-3#2]
i know there some issue  with upload of image ...but i dont know http://192.168.1.66:8081/api why you give this url there

**Comment by adeel399** [comment]
uploadPhoto(img) {
    
    const fileTransfer: FileTransferObject = this.transfer.create();
  
    let options: FileUploadOptions = {
      fileKey: 'photo',
      fileName: 'photo',
      chunkedMode: false,
      mimeType: "image/jpeg",
      headers: { Connection: "close"}
    }
  console.log(img);
    fileTransfer.upload(img, 'http://192.168.1.66:8081/api', options).then( data => {

      this.show(data ,img);

    }, (err) => {
      console.log(err);
      this.loader.dismiss(); 
    });

  }

**Comment by adeel399** [comment]
kindly help

**Comment by hitmacreed** [comment]
> i know there some issue with upload of image ...but i dont know http://192.168.1.66:8081/api why you give this url there

Thats my ip adrees for my local server. You must change to your ipv4 confing

**Comment by adeel399** [comment]
What will be mine i am using window localhost ...

**Comment by adeel399** [comment]
How can i get this address plz eladorate a bit

**Comment by adeel399** [comment]
Its not solved sir

**Comment by hitmacreed** [comment]
> Its not solved sir

U will need to  go to cmd and write ipconfig and it will show u the ipv4.
But thats how i made my backend, you can make it how u want , i did int  on localhost with node js. If u go to the folder backend its already made u will nedd only a key from cloudvision.

**Comment by adeel399** [comment]
Yeah i replaced the colud vision json file...
The issue in file transferr upload...

**Comment by hitmacreed** [comment]
@adeel399 pls verify that you have install hte node js dependecies and the right ip adress

**Comment by adeel399** [comment]
Yeah node js depedancy already installed i am also able to built the app on android too..but ipaddress i did not write..
So in cmd add ipconfig andcthe ipv4 adress add there is filetransfer upload fuction right

**Comment by adeel399** [comment]
And what about the index file in backend folder somthing ro add there

**Comment by hitmacreed** [comment]
> node js depedancy already installed i am also able to built the app on android too..but ipaddress i did not write..

Yes it shloud Work fine , dont forget to start the server inside backend folder

**Comment by adeel399** [comment]
How ?

**Comment by adeel399** [comment]
I know a bit just wanna confirm your exact step about start server in
backend

**Comment by hitmacreed** [comment]
> I know a bit just wanna confirm your exact step about start server in backend

just start the server inside backend folder

By running` npm start index.js`

Thanks closing thread :)
